---
title: "App_chicken_scratch"
author: "Rachel Greenlee"
date: "9/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
mort <- read.csv("https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv", header = TRUE)

```


```{r}
# create subset with just 2010 data
mort_2010 <- subset(mort, Year == "2010")

# group by state and disease, with new variables showing the sum of deaths & pop in that grouping
mort_2010 <- mort_2010 %>%
          group_by(State, ICD.Chapter) %>%
          summarize(tot_deaths = sum(Deaths), tot_pop = sum(Population))

# create new variable crude_rate to recalculate the crude rate at this grouping level
mort_2010$crude_rate <- round((mort_2010$tot_deaths / mort_2010$tot_pop) * 100000, 4)
  


```

```{r}
ggplot(mort_2010, aes(x = crude_rate, y = reorder(State, crude_rate))) +
      geom_bar(stat = "identity") + 
      labs(title = "2010 Crude Mortality Rates, by State", 
           x = "Crude Rate (Per 100,000)", 
           y ="State")
```

