---
title: "App_chicken_scratch"
author: "Rachel Greenlee"
date: "9/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
mort <- read.csv("https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv", header = TRUE)

```


```{r}


# collapse State rows 
mort_national <- mort %>%
          group_by(ICD.Chapter,Year) %>%
          summarize(tot_deaths = sum(Deaths), tot_pop = sum(Population))

# create national average crude rates by cause over the years
mort_national$national_crude_rate <- round((mort_national$tot_deaths / mort_national$tot_pop) * 100000, 4)

# columns we want to paste together in both dataframes
cols <- c( 'ICD.Chapter' , 'Year')

# create that new column in mort_national
mort_national$join <- apply( mort_national[ , cols] , 1 , paste , collapse = "-" )

# create that new column in mort
mort$join <- apply( mort[ , cols] , 1 , paste , collapse = "-" )

# join with state level data in new df
mort_comp <- left_join(mort, mort_national, by = "join")

# create column that shows pos/neg difference from national crude rate
mort_comp$nat_diff <- round(mort_comp$national_crude_rate - mort_comp$Crude.Rate, 4)

# create pos/neg for diverage bar chart
mort_comp$diff_type <- ifelse(mort_comp$nat_diff < 0, "below", "above")

```

```{r}

# remove later
mort_comp_test <- mort_comp %>%
  filter(State == "KY", 
         ICD.Chapter.x == "Certain infectious and parasitic diseases")

# try diverging barchart
ggplot(mort_comp_test, aes(x = Year.x, y = nat_diff, label = nat_diff)) + 
  geom_bar(stat='identity', aes(fill=diff_type), width=.5)  +
  scale_fill_manual(name="Compared to National Crude Rate", 
                    labels = c("Above National Average", "Below National Average"), 
                    values = c("above"="#00ba38", "below"="#f8766d")) + 
  labs(subtitle="calculated from available data'", 
       title= "I need a title")
```

```{r}
ggplot(mort_comp_test, aes( x = Year.x)) + 
  geom_line(aes(y = Crude.Rate), color = "darkred") + 
  geom_line(aes(y = national_crude_rate), color="steelblue", linetype="twodash") 
```

